### ISSUE TITLE
Save plots

### ISSUE THREAD

**Issue by KwatMDPhD** [KwatMDPhD/gsea.py#11]

**Comment by KwatME** [comment]
http://juliaplots.org/PlotlyJS.jl/stable/api/#PlotlyBase.savefig-Tuple{Plot,AbstractString}

https://github.com/KwatME/kwat.py/blob/b94d5b2e8552652eafde8335cd2fc65d3b800204/kraft/score_set.py

**Comment by KwatME** [comment]
ETA weeks.
