### ISSUE TITLE
Match signal to noise with the desktop (java) application

### ISSUE THREAD

**Issue by KwatMDPhD** [KwatMDPhD/gsea.py#14]
@davideby @pablotamayo

How is the desktop S2N implemented? Mine is a bit different from that one.

**Comment by davideby** [comment]
Hi @KwatME
The formulas for the metrics as implemented in the Desktop are given in the User Guide.  Here's a direct link to the [relevant section](https://www.gsea-msigdb.org/gsea/doc/GSEAUserGuideFrame.html?_Metrics_for_Ranking).

**Comment by davideby** [comment]
Oh, be sure to check out the important footnote there about adjusting σ based on the value of μ.  A similar adjustment applies to tTest as well.

Also, this is a spot where NaN can creep in to the computation due to zero values in the denominator.

**Comment by ACastanza** [comment]
Hey David,

Yeah, I linked the user guide and mentioned the σ adjustment, but (apparently) it still comes out slightly different - although I haven't been able to run the latest test version myself yet. My guess is that its a rounding error, or rather, somewhere where python and java handle floating point values slightly differently.

**Comment by davideby** [comment]
Or it could be FP calculations in the Julia code, I guess.  How different is it?

**Comment by KwatME** [comment]
This is my implementation of S2N. Let me know if anything is wrong. https://github.com/KwatME/kwat.py/blob/master/kwat/array_array.py

**Comment by davideby** [comment]
These are FP numbers, so you can't test them for zero directly as in `me0 == 0`, etc.  It is *exceedingly* unlikely that those values will be exactly zero due to FP rounding and inexactness. so you need to test for `isNearlyZero()` instead, otherwise it's (almost) as if the adjustment doesn't even exist.  It's basically checking against a small epsilon.

For the Java computation, we use `Math.abs(value) <= 1e-9d` for `isNearlyZero()`.  Since it's informative to the topic, here's the code comment associated with that test:
```
See https://randomascii.wordpress.com/2012/02/25/comparing-floating-point-numbers-2012-edition/
Since we are only concerned with testing values very close to zero here, we don't deal with ULPs 
as discussed in the above article.  It's enough to use a small epsilon instead.
Since our computations are done in Doubles, we use the equivalent of the C++ DBL_EPSILON
instead of FLT_EPSILON (see http://www.cplusplus.com/reference/cfloat/)
```

The full test looks like this:
```
double minallowed = XMath.isNearlyZero(mean) ? 0.20 : (0.20 * Math.abs(mean));
stddev = Math.max(stddev, minallowed);
```

FWIW, the old Java code used to do something very similar to yours, but we fixed it a couple of years ago after discussing it with Jill and Pablo in one of our GSEA group meetings.

**Comment by KwatME** [comment]
Thank you @davideby !

**Comment by ACastanza** [comment]
Not sure if this has the fixed sigma correction yet, but results are still looking weird, particularly the Qvalues.

No q-values were returned under .459 through this GSEA implementation

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/acastanza/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/acastanza/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



WP_FATTY_ACID_OMEGA_OXIDATION | 0.73388065 | 0.001 | 0.45952544
-- | -- | -- | --
WP_OXIDATION_BY_CYTOCHROME_P450 | 0.52454221 | 0.001 | 0.45952544
WP_NONALCOHOLIC_FATTY_LIVER_DISEASE | -0.6653779 | 0.001 | 0.45952544
WP_TCA_CYCLE_IN_SENESCENCE | -0.8293777 | 0.001 | 0.45952544
WP_MITOCHONDRIAL_CIV_ASSEMBLY | -0.8122529 | 0.002 | 0.70572001
WP_MITOCHONDRIAL_CIII_ASSEMBLY | -0.8728257 | 0.002 | 0.70572001

</body>

</html>

but desktop GSEA returned:

235 / 470 gene sets are upregulated in phenotype 0
12 gene sets are significant at FDR < 25%



1 | WP_NONALCOHOLIC_FATTY_LIVER_DISEASE | Details ... | 153 | 0.67 | 2.08 | 0.000 | 0.070 | 0.055 | 1813 | tags=42%, list=5%, signal=44%
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
2 | WP_ENDOPLASMIC_RETICULUM_STRESS_RESPONSE_IN_CORONAVIRUS_INFECTION | Details ... | 47 | 0.49 | 1.94 | 0.002 | 0.181 | 0.244 | 2284 | tags=23%, list=7%, signal=25%
3 | WP_TCELL_ANTIGEN_RECEPTOR_TCR_PATHWAY_DURING_STAPHYLOCOCCUS_AUREUS_INFECTION | Details ... | 62 | 0.47 | 1.86 | 0.014 | 0.252 | 0.421 | 7769 | tags=40%, list=23%, signal=52%
4 | WP_MITOCHONDRIAL_CIV_ASSEMBLY | Details ... | 34 | 0.84 | 1.80 | 0.000 | 0.349 | 0.586 | 3316 | tags=76%, list=10%, signal=85%
5 | WP_NAD_METABOLISM_IN_ONCOGENEINDUCED_SENESCENCE_AND_MITOCHONDRIAL_DYSFUNCTIONASSOCIATED_SENESCENCE | Details ... | 22 | 0.60 | 1.79 | 0.014 | 0.301 | 0.601 | 2271 | tags=32%, list=7%, signal=34%
6 | WP_MITOCHONDRIAL_COMPLEX_I_ASSEMBLY_MODEL_OXPHOS_SYSTEM | Details ... | 56 | 0.80 | 1.77 | 0.010 | 0.294 | 0.645 | 5060 | tags=75%, list=15%, signal=88%
7 | WP_ELECTRON_TRANSPORT_CHAIN_OXPHOS_SYSTEM_IN_MITOCHONDRIA | Details ... | 103 | 0.84 | 1.76 | 0.002 | 0.270 | 0.659 | 1813 | tags=72%, list=5%, signal=76%
8 | WP_METABOLIC_REPROGRAMMING_IN_COLON_CANCER | Details ... | 42 | 0.58 | 1.76 | 0.022 | 0.244 | 0.670 | 4928 | tags=43%, list=14%, signal=50%
9 | WP_ID_SIGNALING_PATHWAY | Details ... | 16 | 0.67 | 1.75 | 0.012 | 0.237 | 0.689 | 3887 | tags=44%, list=11%, signal=49%
10 | WP_OXIDATIVE_PHOSPHORYLATION | Details ... | 60 | 0.85 | 1.74 | 0.006 | 0.218 | 0.695 | 1813 | tags=75%, list=5%, signal=79%
11 | WP_NAD_METABOLISM | Details ... | 16 | 0.58 | 1.72 | 0.012 | 0.242 | 0.736 | 2271 | tags=31%, list=7%, signal=33%
12 | WP_7Q1123_COPY_NUMBER_VARIATION_SYNDROME | Details ... | 96 | 0.40 | 1.72 | 0.016 | 0.230 | 0.752 | 3340 | tags=24%, list=10%, signal=26%
13 | WP_GLYCOLYSIS_AND_GLUCONEOGENESIS | Details ... | 45 | 0.55 | 1.72 | 0.018 | 0.213 | 0.753 | 4928 | tags=44%, list=14%, signal=52%
14 | WP_HEREDITARY_LEIOMYOMATOSIS_AND_RENAL_CELL_CARCINOMA_PATHWAY | Details ... | 20 | 0.53 | 1.70 | 0.030 | 0.229 | 0.787 | 4474 | tags=30%, list=13%, signal=35%
15 | WP_SELECTIVE_EXPRESSION_OF_CHEMOKINE_RECEPTORS_DURING_TCELL_POLARIZATION | Details ... | 29 | 0.60 | 1.69 | 0.006 | 0.227 | 0.797 | 6164 | tags=55%, list=18%, signal=67%
16 | WP_MITOCHONDRIAL_CIII_ASSEMBLY | Details ... | 16 | 0.90 | 1.69 | 0.000 | 0.213 | 0.797 | 928 | tags=75%, list=3%, signal=77%
17 | WP_UREA_CYCLE_AND_ASSOCIATED_PATHWAYS | Details ... | 24 | 0.66 | 1.69 | 0.015 | 0.201 | 0.798 | 4131 | tags=54%, list=12%, signal=62%
18 | WP_PROTEASOME_DEGRADATION | Details ... | 62 | 0.46 | 1.64 | 0.058 | 0.279 | 0.884 | 10254 | tags=53%, list=30%, signal=76%
19 | WP_TCA_CYCLE_AND_DEFICIENCY_OF_PYRUVATE_DEHYDROGENASE_COMPLEX_PDHC | Details ... | 16 | 0.76 | 1.62 | 0.020 | 0.309 | 0.908 | 3078 | tags=63%, list=9%, signal=69%
20 | WP_SARSCOV2_MITOCHONDRIAL_INTERACTIONS | Details ... | 32 | 0.48 | 1.59 | 0.030 | 0.363 | 0.936 | 1190 | tags=22%, list=4%, signal=23%

**Comment by ACastanza** [comment]
Also, it new-GSEA seems to be doing the second phenotype vs the first phenotype by default instead of the first phenotype  vs the second phenotype based on the switched direction of the enrichment score sign

**Comment by KwatME** [comment]
I need to talk to @pablotamayo to make sure that I'm competing the null distribution as the old method does. I'll get back to you. And thank you for the detailed information @ACastanza . Super useful.

**Comment by KwatME** [comment]
#19

**Comment by KwatME** [comment]
ETA weeks.
