### ISSUE TITLE
Finalize parameters

### ISSUE THREAD

**Issue by KwatMDPhD** [KwatMDPhD/gsea.py#9]
@ACastanza @alex-wenzel

**Comment by ACastanza** [comment]
For multi-word values like signal to noise, please use avoid the use of spaces in value names to prevent parsing issues (i.e. signal_to_noise or signal2noise, instead of "signal to noise").

**Comment by KwatME** [comment]
Will use signal_to_noise. Will use lowercase with underscore.

**Comment by ACastanza** [comment]
Parameter names need some work as well.

sc_el_sa for the gene-by-sample matrix and se_el_ for the gene sets dict are way too similar, also, names like "sc_el_sa" "se_el_" and "ta" are bordering on nonsensical.

Again noting my prefered order of parameters below:

run_gsea(
sc_el_sa,
se_el_,
la_,
pe="label",
n_pe=1000,
fu=options.rme,
mi=5,
ma=500,
al=options.eme,
we=1.0,
no=None,
se=1729,
n_pl=25,
ad=None,
pa="gsea_results",
)

but I would suggest simple names for the first three like; dataset, genesets, labels or something similarly obvious as to what each parameter actually is.

I would encourage you to go through the parameter names and options from the current GSEA desktop release and use those names and values as a starting place for naming these parameters and options.

**Comment by KwatME** [comment]
ETA few days.
